title: DuploJS
url: https://duplojs.github.io
baseurl: /documentation
email: campani.mathieu@gmail.com
github_username: mathcovax
permalink: pretty
logo: "/assets/images/logo.svg"

# Build settings
keep_files: 
  - en
source: .
destination: _site
theme: just-the-docs
plugins:
  - jekyll-feed
exclude: 
  - en/
