title: DuploJS
url: https://duplojs.github.io
baseurl: /documentation
email: campani.mathieu@gmail.com
github_username: mathcovax
permalink: pretty
logo: "/assets/images/logo.svg"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Build settings
source: .
destination: _site
theme: just-the-docs
plugins:
  - jekyll-feed
  - md_hl_syntax_to_liquid
exclude: 
  - fr/
