title: DuploJS
url: https://docs.duplojs.dev
baseurl: /fr/latest
email: campani.mathieu@gmail.com
github_username: mathcovax
logo: "/assets/images/logo.svg"
favicon_ico: "/assets/images/logo.ico"
color_scheme: yellow_light

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

permalink: pretty
source: .
theme: just-the-docs
plugins:
  - jekyll-feed

collections:
  resources:
    output: true

just_the_docs:
  collections:
    resources:
      name: Ressources
